package com.callguard.core

/** Text of the app's own screens. (Warnings, summaries and advice live in [Strings] and [WarningPlans].) */
enum class Ui {
    TITLE, START, CALLER_ID, ACCESS_ON, ACCESS_OFF, LANGUAGES, TEST, STOP, FAMILY_CHOOSE, FAMILY_CONTACT_FMT, FAMILY_ALERT,
    TRANSCRIPT_EMPTY, RISK_LOW, RISK_MEDIUM, RISK_HIGH, ALERT_HIGH, ALERT_MEDIUM,
    SUMMARY_TITLE, READ_ALOUD, SHARE, HELPLINE, DISMISS, TECH_SHOW, TECH_HIDE, NO_VOICE_FMT,
    GR_NEXT, GR_BACK, GR_DONE_TICK, GR_LANG_TITLE, GR_LANG_WHY, GR_PERMS_TITLE, GR_PERMS_WHY, GR_PERMS_SETTINGS, GR_MODELS_LATER, GR_PRACTICE_TITLE, GR_PRACTICE_WHY, GR_PRACTICE_START, GR_FINISH_TITLE, GR_FINISH_BODY, GR_FINISH, GR_HELP_OTHERS, PR_TITLE, PR_SAYS, PR_START, PR_RINGING, PR_WARNING, PR_DONE, HP_TITLE, HP_INTRO, HP_STEP1, HP_STEP2, HP_STEP3, HOME_SETTINGS, HOME_MORE, HOME_LESS, HOME_TURN_OFF, HOME_PRACTICE, HOME_LAST_CALL, ST_METRICS_FMT, ST_METRICS_NONE, ST_SECTION_HELP,
    MY_LANGUAGE, MY_LANGUAGE_HINT, ADVANCED_SHOW, ADVANCED_HIDE, LANG_INTRO, LANG_EXAMPLE, LANG_SCREEN, LANG_SPOKEN, LANG_SUMMARY, LANG_FAMILY,
    OPT_AUTO_CALL, OPT_SAME_AS_SCREEN, OPT_MATCH_CALL, DONE,
    MI_SHARE_MODELS, MI_SHARE_APP, MI_SHARE_BUILDING_FMT, MI_SHARE_NONE, MI_SHARE_NO_SPACE, MI_SHARE_FAILED, MI_DL_WIFI, MI_DL_MOBILE, MI_DL_PROGRESS_FMT, MI_DL_FAILED_FMT, MI_NOT_PACK, MI_PACK_HINT, MI_TITLE, MI_INTRO, MI_PICK, MI_WORKING_FMT, MI_OK_VERIFIED, MI_OK_UNVERIFIED, MI_NOT_MODEL, MI_WRONG_SIZE, MI_NO_SPACE, MI_FAILED, MI_RESTART, MI_STATUS_FMT,
    PACK_UPDATE, PACK_VERSION_FMT, PACK_UPDATED, PACK_UP_TO_DATE, PACK_REJECTED, PACK_OFFLINE, FA_REMOVE, FA_ADD_ANOTHER, BEEP_ON, BEEP_OFF, BEEP_HINT, SETUP_STEP_FMT, SETUP_ALL_SET, SETUP_MARK_DONE, SETUP_SKIP, SETUP_LATER_TITLE, OPT_YES, OPT_NO, FA_OPEN, FA_TITLE, FA_SENDS, FA_NEVER, FA_WHEN, FA_SAMPLE, FA_CALLER, FA_AUTO_ON, FA_AUTO_OFF, FA_TEST, FA_LOG, FA_LOG_EMPTY, FA_NEED_CONTACT, FA_SENT_LINE, FA_LOG_SENT, FA_LOG_FAILED, FA_LOG_TEST,
    BLOCK_NUMBER, UNBLOCK_NUMBER, BLOCK_NOTE, BLOCK_LIST_FMT, BLOCK_CLEAR,
    RECOVERY_BUTTON, RECOVERY_TITLE, RECOVERY_INTRO, RECOVERY_WHAT, BANK_NUMBER, BANK_NUMBER_SET, URGENT_FIRST,
    PRIVACY, PRIVACY_BODY, ERASE_ALL, ERASE_CONFIRM, ERASE_DONE,
    SETTINGS, SETTINGS_INTRO, SCOPE_LABEL, SCOPE_UNKNOWN, SCOPE_ALL, SCOPE_HINT,
    FEEDBACK_Q, FEEDBACK_YES, FEEDBACK_NO, FEEDBACK_UNSURE, FEEDBACK_SAVED, FEEDBACK_SAFE_NOTE,
    // Wave 2
    NOTIF_WATCHING_TITLE, NOTIF_WATCHING_BODY, NOTIF_LISTENING_TITLE, NOTIF_LISTENING_BODY,
    TILE_ON, TILE_OFF,
    TR_TITLE, TR_BODY, TR_CHECK_FMT, TR_CHECK_YES, TR_CHECK_NO, TR_READ_ALOUD,
    LIVE_ALERT_PUBLIC_TITLE, COACHING_LABEL,
    UNPROTECTED_NUDGE_FMT, UNPROTECTED_DISMISS,
    HOME_HISTORY, HIST_TITLE, HIST_EMPTY, HIST_REPORTS_TITLE, HIST_BLOCKED_FMT,
    MISSED_BUTTON, MISSED_TITLE, MISSED_INTRO, MISSED_TAG_OTP, MISSED_TAG_THREAT, MISSED_TAG_APP, MISSED_TAG_MONEY, MISSED_TAG_OTHER, MISSED_SAVE, MISSED_SAVED,
    FU_TITLE, FU_FEEDBACK_STEP, FU_RECOVERY_STEP, FU_RECOVERY_WHY, FU_BLOCK_STEP, FU_BLOCK_WHY, FU_FAMILY_STEP, FU_FAMILY_WHY, FU_SKIP, FU_DONE,
    PR_PICK_TITLE, PR_PICK_INTRO,
    ACC_SUGGEST_FMT, ACC_SUGGEST_YES, ACC_SUGGEST_NO,
}

object UiStrings {
    private fun t(en: String, hi: String, te: String) = Triple(en, hi, te)

    private val table: Map<Ui, Triple<String, String, String>> = mapOf(
        Ui.TITLE to t("CallGuard — on-device scam shield", "CallGuard — फ़ोन पर ही चलने वाली ठगी-सुरक्षा", "CallGuard — ఫోన్‌లోనే పనిచేసే స్కామ్ రక్షణ"),
        Ui.START to t("Start monitoring calls", "कॉल की निगरानी शुरू करें", "కాల్ పర్యవేక్షణ ప్రారంభించండి"),
        Ui.CALLER_ID to t("Enable caller-ID check", "कॉलर-आईडी जाँच चालू करें", "కాలర్-ఐడీ తనిఖీ ఆన్ చేయండి"),
        Ui.ACCESS_ON to t("Accessibility mode: ON (tap to turn off)", "सुलभता मोड: चालू (बंद करने के लिए दबाएं)", "యాక్సెసిబిలిటీ మోడ్: ఆన్ (ఆఫ్ చేయడానికి నొక్కండి)"),
        Ui.ACCESS_OFF to t("Accessibility mode: OFF (tap to turn on)", "सुलभता मोड: बंद (चालू करने के लिए दबाएं)", "యాక్సెసిబిలిటీ మోడ్: ఆఫ్ (ఆన్ చేయడానికి నొక్కండి)"),
        Ui.LANGUAGES to t("Languages", "भाषाएँ", "భాషలు"),
        Ui.TEST to t("Test capture now (no call)", "अभी परीक्षण करें (बिना कॉल)", "ఇప్పుడే పరీక్షించండి (కాల్ లేకుండా)"),
        Ui.STOP to t("Stop", "रोकें", "ఆపండి"),
        Ui.FAMILY_CHOOSE to t("Choose a family contact", "परिवार का संपर्क चुनें", "కుటుంబ సభ్యుని కాంటాక్ట్ ఎంచుకోండి"),
        Ui.FAMILY_CONTACT_FMT to t("Family contact: %s (tap to change)", "परिवार का संपर्क: %s (बदलने के लिए दबाएं)", "కుటుంబ కాంటాక్ట్: %s (మార్చడానికి నొక్కండి)"),
        Ui.FAMILY_ALERT to t("Alert a family member", "परिवार के सदस्य को सूचित करें", "కుటుంబ సభ్యునికి తెలియజేయండి"),
        Ui.TRANSCRIPT_EMPTY to t("(transcript appears here)", "(बातचीत का लिखित रूप यहाँ दिखेगा)", "(సంభాషణ ఇక్కడ కనిపిస్తుంది)"),
        Ui.RISK_LOW to t("RISK: LOW", "ख़तरा: कम", "ప్రమాదం: తక్కువ"),
        Ui.RISK_MEDIUM to t("RISK: MEDIUM", "ख़तरा: मध्यम", "ప్రమాదం: మధ్యస్థం"),
        Ui.RISK_HIGH to t("RISK: HIGH", "ख़तरा: अधिक", "ప్రమాదం: అధికం"),
        Ui.ALERT_HIGH to t("⚠ Likely scam — don't share codes, don't install apps.", "⚠ ठगी की आशंका — कोई कोड न बताएं, कोई ऐप इंस्टॉल न करें।", "⚠ మోసం అయ్యే అవకాశం — కోడ్‌లు చెప్పకండి, యాప్‌లు ఇన్‌స్టాల్ చేయకండి."),
        Ui.ALERT_MEDIUM to t("⚠ Suspicious call.", "⚠ संदिग्ध कॉल।", "⚠ అనుమానాస్పద కాల్."),
        Ui.SUMMARY_TITLE to t("Call summary", "कॉल का सारांश", "కాల్ సారాంశం"),
        Ui.READ_ALOUD to t("Read summary aloud", "सारांश पढ़कर सुनाएं", "సారాంశాన్ని చదివి వినిపించండి"),
        Ui.SHARE to t("Share report", "रिपोर्ट साझा करें", "నివేదికను షేర్ చేయండి"),
        Ui.HELPLINE to t("Call helpline 1930", "हेल्पलाइन 1930 पर कॉल करें", "హెల్ప్‌లైన్ 1930కి కాల్ చేయండి"),
        Ui.DISMISS to t("Dismiss", "बंद करें", "మూసివేయండి"),
        Ui.TECH_SHOW to t("Technical details (tap to show)", "तकनीकी जानकारी (दिखाने के लिए दबाएं)", "సాంకేతిక వివరాలు (చూపడానికి నొక్కండి)"),
        Ui.TECH_HIDE to t("Technical details (tap to hide)", "तकनीकी जानकारी (छिपाने के लिए दबाएं)", "సాంకేతిక వివరాలు (దాచడానికి నొక్కండి)"),
        Ui.NO_VOICE_FMT to t("No %s voice is installed on this phone", "इस फ़ोन में %s आवाज़ इंस्टॉल नहीं है", "ఈ ఫోన్‌లో %s స్వరం ఇన్‌స్టాల్ చేయలేదు"),
        Ui.GR_NEXT to t("Next", "आगे", "తర్వాత"),
        Ui.GR_BACK to t("Back", "पीछे", "వెనుకకు"),
        Ui.GR_DONE_TICK to t("Done ✓", "हो गया ✓", "పూర్తయింది ✓"),
        Ui.GR_LANG_TITLE to t("Choose your language", "अपनी भाषा चुनें", "మీ భాషను ఎంచుకోండి"),
        Ui.GR_LANG_WHY to t("CallGuard will speak and write to you in this language.", "CallGuard आपसे इसी भाषा में बोलेगा और लिखेगा।", "CallGuard మీతో ఈ భాషలో మాట్లాడుతుంది, రాస్తుంది."),
        Ui.GR_PERMS_TITLE to t("Allow listening and warnings", "सुनने और चेतावनी की अनुमति दें", "వినడానికి, హెచ్చరించడానికి అనుమతించండి"),
        Ui.GR_PERMS_WHY to t("CallGuard needs to hear the call, know when it starts, and show warnings. All of it stays on this phone.", "CallGuard को कॉल सुनना, यह जानना कि कॉल कब शुरू हुई, और चेतावनी दिखाना है। सब कुछ इसी फ़ोन पर रहता है।", "CallGuard కాల్ వినాలి, అది ఎప్పుడు మొదలైందో తెలుసుకోవాలి, హెచ్చరికలు చూపాలి. ఇదంతా ఈ ఫోన్‌లోనే ఉంటుంది."),
        Ui.GR_PERMS_SETTINGS to t("Open app settings to allow", "अनुमति के लिए ऐप सेटिंग खोलें", "అనుమతించడానికి యాప్ సెట్టింగ్‌లు తెరవండి"),
        Ui.GR_MODELS_LATER to t("English only for now", "अभी सिर्फ़ अंग्रेज़ी", "ప్రస్తుతానికి ఆంగ్లం మాత్రమే"),
        Ui.GR_PRACTICE_TITLE to t("Try a practice call", "अभ्यास कॉल आज़माएं", "ప్రాక్టీస్ కాల్ ప్రయత్నించండి"),
        Ui.GR_PRACTICE_WHY to t("Hear and see what a warning looks like. Nothing is recorded.", "देखें और सुनें कि चेतावनी कैसी होती है। कुछ रिकॉर्ड नहीं होता।", "హెచ్చరిక ఎలా ఉంటుందో చూడండి, వినండి. ఏదీ రికార్డ్ కాదు."),
        Ui.GR_PRACTICE_START to t("Start practice call", "अभ्यास कॉल शुरू करें", "ప్రాక్టీస్ కాల్ మొదలుపెట్టండి"),
        Ui.GR_FINISH_TITLE to t("You are ready", "आप तैयार हैं", "మీరు సిద్ధంగా ఉన్నారు"),
        Ui.GR_FINISH_BODY to t("CallGuard now protects calls from numbers you do not know. You can close the app.", "CallGuard अब अनजान नंबरों की कॉल की सुरक्षा करेगा। आप ऐप बंद कर सकते हैं।", "CallGuard ఇప్పుడు మీకు తెలియని నంబర్ల కాల్స్‌ను రక్షిస్తుంది. మీరు యాప్‌ను మూసివేయవచ్చు."),
        Ui.GR_FINISH to t("Finish", "पूरा करें", "పూర్తి చేయండి"),
        Ui.GR_HELP_OTHERS to t("Help a family member set up", "परिवार के किसी सदस्य को सेट करने में मदद करें", "కుటుంబ సభ్యునికి సెటప్ చేయడంలో సహాయం చేయండి"),
        Ui.PR_TITLE to t("Practice call", "अभ्यास कॉल", "ప్రాక్టీస్ కాల్"),
        Ui.PR_SAYS to t("Pretend a caller says:", "मान लीजिए कॉल करने वाला कहता है:", "కాల్ చేసినవారు ఇలా అన్నారనుకోండి:"),
        Ui.PR_START to t("Start practice call", "अभ्यास कॉल शुरू करें", "ప్రాక్టీస్ కాల్ మొదలుపెట్టండి"),
        Ui.PR_RINGING to t("Practice call in progress ...", "अभ्यास कॉल चल रही है ...", "ప్రాక్టీస్ కాల్ జరుగుతోంది ..."),
        Ui.PR_WARNING to t("WARNING: this looks like a scam. Do not share codes. Hang up.", "चेतावनी: यह ठगी लग रही है। कोई कोड न बताएं। फ़ोन काट दें।", "హెచ్చరిక: ఇది మోసంలా ఉంది. కోడ్‌లు చెప్పకండి. ఫోన్ కట్ చేయండి."),
        Ui.PR_DONE to t("That is what you will see and hear. Nothing was recorded.", "आप यही देखेंगे और सुनेंगे। कुछ रिकॉर्ड नहीं हुआ।", "మీరు చూసేదీ, వినేదీ ఇదే. ఏదీ రికార్డ్ కాలేదు."),
        Ui.HP_TITLE to t("Help a family member", "परिवार के सदस्य की मदद करें", "కుటుంబ సభ్యునికి సహాయం చేయండి"),
        Ui.HP_INTRO to t("Set up CallGuard on a parent's or relative's phone in three steps.", "माता-पिता या रिश्तेदार के फ़ोन पर तीन चरणों में CallGuard सेट करें।", "తల్లిదండ్రులు లేదా బంధువుల ఫోన్‌లో మూడు దశల్లో CallGuard సెటప్ చేయండి."),
        Ui.HP_STEP1 to t("1. Send them the app.", "1. उन्हें ऐप भेजें।", "1. వారికి యాప్ పంపండి."),
        Ui.HP_STEP2 to t("2. Send them the language pack.", "2. उन्हें भाषा पैक भेजें।", "2. వారికి భాషా ప్యాక్ పంపండి."),
        Ui.HP_STEP3 to t("3. On their phone: open the app file and allow the install. Open the language pack file and choose CallGuard. Then open CallGuard and follow Get ready.", "3. उनके फ़ोन पर: ऐप फ़ाइल खोलकर इंस्टॉल की अनुमति दें। भाषा पैक फ़ाइल खोलकर CallGuard चुनें। फिर CallGuard खोलकर \"तैयार हों\" के चरण पूरे करें।", "3. వారి ఫోన్‌లో: యాప్ ఫైల్ తెరిచి ఇన్‌స్టాల్‌కు అనుమతించండి. భాషా ప్యాక్ ఫైల్ తెరిచి CallGuard ను ఎంచుకోండి. తర్వాత CallGuard తెరిచి \"సిద్ధం అవ్వండి\" దశలు పూర్తి చేయండి."),
        Ui.HOME_SETTINGS to t("Settings", "सेटिंग्स", "సెట్టింగ్‌లు"),
        Ui.HOME_MORE to t("More", "और", "మరిన్ని"),
        Ui.HOME_LESS to t("Fewer options", "कम विकल्प", "తక్కువ ఎంపికలు"),
        Ui.HOME_TURN_OFF to t("Turn off protection", "सुरक्षा बंद करें", "రక్షణను ఆఫ్ చేయండి"),
        Ui.HOME_PRACTICE to t("Try a practice call", "अभ्यास कॉल आज़माएं", "ప్రాక్టీస్ కాల్ ప్రయత్నించండి"),
        Ui.HOME_LAST_CALL to t("Last call", "पिछली कॉल", "చివరి కాల్"),
        Ui.ST_METRICS_FMT to t("Last setup: %s, %d taps", "पिछला सेटअप: %s, %d टैप", "చివరి సెటప్: %s, %d ట్యాప్‌లు"),
        Ui.ST_METRICS_NONE to t("No setup timing yet.", "अभी कोई सेटअप समय नहीं।", "ఇంకా సెటప్ సమయం లేదు."),
        Ui.ST_SECTION_HELP to t("Help and testing", "मदद और परीक्षण", "సహాయం మరియు పరీక్ష"),
        Ui.MY_LANGUAGE to t("My language", "मेरी भाषा", "నా భాష"),
        Ui.MY_LANGUAGE_HINT to t("Choose once. Menus, warnings, summaries and messages to family will use it. Warnings follow the language of the call.", "एक बार चुनें। मेन्यू, चेतावनी, सारांश और परिवार को संदेश इसी में होंगे। चेतावनी कॉल की भाषा में आएगी।", "ఒకసారి ఎంచుకోండి. మెనూలు, హెచ్చరికలు, సారాంశాలు, కుటుంబానికి సందేశాలు ఇందులోనే ఉంటాయి. హెచ్చరిక కాల్ భాషలో వస్తుంది."),
        Ui.ADVANCED_SHOW to t("Advanced: choose each one separately", "उन्नत: हर एक अलग से चुनें", "అధునాతన: ప్రతిదాన్ని విడిగా ఎంచుకోండి"),
        Ui.ADVANCED_HIDE to t("Hide advanced options", "उन्नत विकल्प छिपाएं", "అధునాతన ఎంపికలను దాచండి"),
        Ui.LANG_INTRO to t("Choose how CallGuard talks to you. You can change these any time.", "चुनें कि CallGuard आपसे किस भाषा में बात करे। आप इन्हें कभी भी बदल सकते हैं।", "CallGuard మీతో ఏ భాషలో మాట్లాడాలో ఎంచుకోండి. వీటిని ఎప్పుడైనా మార్చవచ్చు."),
        Ui.LANG_EXAMPLE to t("Example: speak Telugu on calls, read summaries in English.", "उदाहरण: कॉल पर तेलुगु बोलें, सारांश अंग्रेज़ी में पढ़ें।", "ఉదాహరణ: కాల్‌లో తెలుగు మాట్లాడండి, సారాంశాన్ని ఆంగ్లంలో చదవండి."),
        Ui.LANG_SCREEN to t("Screen language", "स्क्रीन की भाषा", "స్క్రీన్ భాష"),
        Ui.LANG_SPOKEN to t("Spoken warning", "बोलकर चेतावनी", "మాటల్లో హెచ్చరిక"),
        Ui.LANG_SUMMARY to t("Call summary", "कॉल का सारांश", "కాల్ సారాంశం"),
        Ui.LANG_FAMILY to t("Message to family", "परिवार को संदेश", "కుటుంబానికి సందేశం"),
        Ui.OPT_AUTO_CALL to t("Auto (follow the call)", "अपने आप (कॉल की भाषा में)", "ఆటో (కాల్ భాషలో)"),
        Ui.OPT_SAME_AS_SCREEN to t("Same as screen", "स्क्रीन जैसी", "స్క్రీన్ భాషలోనే"),
        Ui.OPT_MATCH_CALL to t("Match the call", "कॉल की भाषा में", "కాల్ భాషలో"),
        Ui.DONE to t("Done", "हो गया", "పూర్తయింది"),
        Ui.MI_SHARE_MODELS to t("Share language pack with a family member", "परिवार के किसी सदस्य को भाषा पैक भेजें", "కుటుంబ సభ్యునికి భాషా ప్యాక్‌ను పంపండి"),
        Ui.MI_SHARE_APP to t("Share the CallGuard app itself", "CallGuard ऐप ही भेजें", "CallGuard యాప్‌నే పంపండి"),
        Ui.MI_SHARE_BUILDING_FMT to t("Preparing %s ... this takes about a minute.", "%s तैयार हो रहा है ... इसमें लगभग एक मिनट लगता है।", "%s సిద్ధమవుతోంది ... దీనికి సుమారు ఒక నిమిషం పడుతుంది."),
        Ui.MI_SHARE_NONE to t("Nothing to share yet: no language files are installed on this phone.", "अभी भेजने को कुछ नहीं: इस फ़ोन में कोई भाषा फ़ाइल नहीं है।", "ఇంకా పంపడానికి ఏమీ లేదు: ఈ ఫోన్‌లో భాషా ఫైళ్లు లేవు."),
        Ui.MI_SHARE_NO_SPACE to t("Not enough free space to prepare the file. Free some space and try again.", "फ़ाइल तैयार करने के लिए पर्याप्त जगह नहीं है। जगह खाली करके फिर कोशिश करें।", "ఫైల్ సిద్ధం చేయడానికి తగినంత స్థలం లేదు. స్థలం ఖాళీ చేసి మళ్లీ ప్రయత్నించండి."),
        Ui.MI_SHARE_FAILED to t("Could not prepare the file.", "फ़ाइल तैयार नहीं हो सकी।", "ఫైల్ సిద్ధం కాలేదు."),
        Ui.MI_DL_WIFI to t("Download my language on Wi-Fi (about 0.9 GB)", "वाई-फ़ाई पर मेरी भाषा डाउनलोड करें (लगभग 0.9 GB)", "వై-ఫైలో నా భాషను డౌన్‌లోడ్ చేయండి (సుమారు 0.9 GB)"),
        Ui.MI_DL_MOBILE to t("Download using mobile data instead", "इसके बजाय मोबाइल डेटा से डाउनलोड करें", "బదులుగా మొబైల్ డేటాతో డౌన్‌లోడ్ చేయండి"),
        Ui.MI_DL_PROGRESS_FMT to t("Downloading: %d%%. You can leave this screen; Android continues in the background.", "डाउनलोड हो रहा है: %d%%। आप इस स्क्रीन से जा सकते हैं; Android पीछे जारी रखेगा।", "డౌన్‌లోడ్ అవుతోంది: %d%%. మీరు ఈ స్క్రీన్ నుండి వెళ్లవచ్చు; Android వెనుక కొనసాగిస్తుంది."),
        Ui.MI_DL_FAILED_FMT to t("%d file(s) failed the safety check or the download and were not used. Try again.", "%d फ़ाइल सुरक्षा जाँच या डाउनलोड में विफल रही और उपयोग नहीं हुई। फिर कोशिश करें।", "%d ఫైల్(లు) భద్రతా తనిఖీ లేదా డౌన్‌లోడ్‌లో విఫలమయ్యాయి, వాడబడలేదు. మళ్లీ ప్రయత్నించండి."),
        Ui.MI_NOT_PACK to t("this zip does not contain CallGuard model files", "इस ज़िप में CallGuard की मॉडल फ़ाइलें नहीं हैं", "ఈ జిప్‌లో CallGuard మోడల్ ఫైళ్లు లేవు"),
        Ui.MI_PACK_HINT to t("Easiest: choose the language pack file you were given (callguard-models.zip). Or open that file from your Files app or a chat and pick CallGuard.", "सबसे आसान: आपको दी गई भाषा पैक फ़ाइल (callguard-models.zip) चुनें। या उस फ़ाइल को फ़ाइल्स ऐप या चैट से खोलकर CallGuard चुनें।", "సులభమైనది: మీకు ఇచ్చిన భాషా ప్యాక్ ఫైల్‌ను (callguard-models.zip) ఎంచుకోండి. లేదా ఆ ఫైల్‌ను ఫైల్స్ యాప్ లేదా చాట్ నుండి తెరిచి CallGuard ను ఎంచుకోండి."),
        Ui.MI_TITLE to t("Get my language files", "मेरी भाषा की फ़ाइलें लें", "నా భాష ఫైళ్లను పొందండి"),
        Ui.MI_INTRO to t("These files let CallGuard understand calls in Hindi and Telugu. They stay on this phone and nothing is uploaded. Advanced: you can also pick the three files one by one.", "ये फ़ाइलें CallGuard को हिंदी और तेलुगु कॉल समझने में मदद करती हैं। ये इसी फ़ोन में रहती हैं और कुछ अपलोड नहीं होता। उन्नत: आप तीनों फ़ाइलें एक-एक करके भी चुन सकते हैं।", "ఈ ఫైళ్లు CallGuard కు హిందీ, తెలుగు కాల్స్ అర్థం చేసుకోవడంలో సహాయపడతాయి. అవి ఈ ఫోన్‌లోనే ఉంటాయి, ఏదీ అప్‌లోడ్ కాదు. అధునాతన: మూడు ఫైళ్లను ఒక్కొక్కటిగా కూడా ఎంచుకోవచ్చు."),
        Ui.MI_PICK to t("Choose the language pack file", "भाषा पैक फ़ाइल चुनें", "భాషా ప్యాక్ ఫైల్‌ను ఎంచుకోండి"),
        Ui.MI_WORKING_FMT to t("Copying %s ...", "%s कॉपी हो रही है ...", "%s కాపీ అవుతోంది ..."),
        Ui.MI_OK_VERIFIED to t("ready ✓", "तैयार ✓", "సిద్ధం ✓"),
        Ui.MI_OK_UNVERIFIED to t("added, but CallGuard does not recognise this file", "जोड़ दी गई, लेकिन CallGuard इस फ़ाइल को नहीं पहचानता", "జోడించబడింది, కానీ CallGuard ఈ ఫైల్‌ను గుర్తించదు"),
        Ui.MI_NOT_MODEL to t("not a model file, skipped", "मॉडल फ़ाइल नहीं है, छोड़ दी गई", "మోడల్ ఫైల్ కాదు, వదిలేశాం"),
        Ui.MI_WRONG_SIZE to t("the size looks wrong (incomplete download?), skipped", "साइज़ ग़लत लगता है (अधूरा डाउनलोड?), छोड़ दी गई", "సైజ్ తప్పుగా ఉంది (అసంపూర్ణ డౌన్‌లోడ్?), వదిలేశాం"),
        Ui.MI_NO_SPACE to t("not enough free space on the phone, skipped", "फ़ोन में पर्याप्त जगह नहीं है, छोड़ दी गई", "ఫోన్‌లో తగినంత ఖాళీ స్థలం లేదు, వదిలేశాం"),
        Ui.MI_FAILED to t("could not be copied, skipped", "कॉपी नहीं हो सकी, छोड़ दी गई", "కాపీ చేయలేకపోయాం, వదిలేశాం"),
        Ui.MI_RESTART to t("Done. Turn protection off and on again so the new models load.", "हो गया। नए मॉडल लोड करने के लिए सुरक्षा बंद करके फिर चालू करें।", "పూర్తయింది. కొత్త మోడల్స్ లోడ్ కావడానికి రక్షణను ఆఫ్ చేసి మళ్లీ ఆన్ చేయండి."),
        Ui.MI_STATUS_FMT to t("Ready: explanations %s, Hindi/Telugu %s", "तैयार: व्याख्या %s, हिंदी/तेलुगु %s", "సిద్ధం: వివరణలు %s, హిందీ/తెలుగు %s"),
        Ui.PACK_UPDATE to t("Update scam-number list (uses the internet once)", "स्कैम नंबर सूची अपडेट करें (एक बार इंटरनेट इस्तेमाल होगा)", "స్కామ్ నంబర్ జాబితాను అప్‌డేట్ చేయండి (ఒకసారి ఇంటర్నెట్ వాడుతుంది)"),
        Ui.PACK_VERSION_FMT to t("Scam-number list version: %s", "स्कैम नंबर सूची संस्करण: %s", "స్కామ్ నంబర్ జాబితా వెర్షన్: %s"),
        Ui.PACK_UPDATED to t("List updated.", "सूची अपडेट हो गई।", "జాబితా అప్‌డేట్ అయింది."),
        Ui.PACK_UP_TO_DATE to t("Already the newest list.", "सूची पहले से नई है।", "జాబితా ఇప్పటికే తాజాది."),
        Ui.PACK_REJECTED to t("The downloaded list did not pass the safety check and was not used.", "डाउनलोड की गई सूची सुरक्षा जाँच में विफल रही और उपयोग नहीं की गई।", "డౌన్‌లోడ్ చేసిన జాబితా భద్రతా తనిఖీలో విఫలమైంది, వాడబడలేదు."),
        Ui.PACK_OFFLINE to t("Could not reach the server. Nothing was changed.", "सर्वर तक नहीं पहुँच सके। कुछ नहीं बदला।", "సర్వర్‌ను చేరుకోలేకపోయాం. ఏమీ మారలేదు."),
        Ui.FA_REMOVE to t("remove", "हटाएं", "తొలగించండి"),
        Ui.FA_ADD_ANOTHER to t("Add another family contact (up to 3)", "एक और परिवार संपर्क जोड़ें (अधिकतम 3)", "మరో కుటుంబ కాంటాక్ట్‌ను జోడించండి (గరిష్టంగా 3)"),
        Ui.BEEP_ON to t("Notice beep for the caller: ON (tap to turn off)", "कॉल करने वाले के लिए सूचना बीप: चालू (बंद करने के लिए दबाएं)", "కాలర్ కోసం నోటీసు బీప్: ఆన్ (ఆఫ్ చేయడానికి నొక్కండి)"),
        Ui.BEEP_OFF to t("Notice beep for the caller: OFF (tap to turn on)", "कॉल करने वाले के लिए सूचना बीप: बंद (चालू करने के लिए दबाएं)", "కాలర్ కోసం నోటీసు బీప్: ఆఫ్ (ఆన్ చేయడానికి నొక్కండి)"),
        Ui.BEEP_HINT to t("A short beep every 15 seconds during an analysed call lets the other person know the call is being checked on this phone. Recommended: some places require people to be told.", "जाँची जा रही कॉल में हर 15 सेकंड पर एक छोटी बीप दूसरे व्यक्ति को बताती है कि कॉल इस फ़ोन पर जाँची जा रही है। सुझाव: कुछ जगहों पर लोगों को बताना ज़रूरी है।", "విశ్లేషిస్తున్న కాల్‌లో ప్రతి 15 సెకన్లకు ఒక చిన్న బీప్, ఈ కాల్ ఈ ఫోన్‌లో తనిఖీ చేయబడుతోందని అవతలి వ్యక్తికి తెలియజేస్తుంది. సూచన: కొన్ని చోట్ల ప్రజలకు తెలియజేయడం తప్పనిసరి."),
        Ui.SETUP_STEP_FMT to t("Step %d of %d", "चरण %d / %d", "దశ %d / %d"),
        Ui.SETUP_ALL_SET to t("All set. CallGuard will watch your calls.", "सब तैयार है। CallGuard आपकी कॉल पर नज़र रखेगा।", "అంతా సిద్ధం. CallGuard మీ కాల్స్‌ను గమనిస్తుంది."),
        Ui.SETUP_MARK_DONE to t("I have done this", "मैंने यह कर लिया", "నేను ఇది చేశాను"),
        Ui.SETUP_SKIP to t("Skip for now", "अभी छोड़ें", "ప్రస్తుతానికి వదిలేయండి"),
        Ui.SETUP_LATER_TITLE to t("Other steps", "बाकी चरण", "మిగతా దశలు"),
        Ui.OPT_YES to t("yes", "हाँ", "అవును"),
        Ui.OPT_NO to t("no", "नहीं", "కాదు"),
        Ui.FA_OPEN to t("Family alert settings", "परिवार अलर्ट सेटिंग", "కుటుంబ అలర్ట్ సెట్టింగ్‌లు"),
        Ui.FA_TITLE to t("Family alert", "परिवार अलर्ट", "కుటుంబ అలర్ట్"),
        Ui.FA_SENDS to t("If you turn this on, CallGuard sends one text message to each family contact you choose (up to 3), containing only: the risk level, up to three scam tactics heard, and (if you allow) the caller's number.", "इसे चालू करने पर CallGuard आपके चुने संपर्क को एक टेक्स्ट संदेश भेजेगा, जिसमें सिर्फ़ ये होगा: ख़तरे का स्तर, सुनी गई अधिकतम तीन ठगी की तरकीबें, और (आपकी अनुमति हो तो) कॉलर का नंबर।", "దీన్ని ఆన్ చేస్తే, CallGuard మీరు ఎంచుకున్న కాంటాక్ట్‌కు ఒక టెక్స్ట్ మెసేజ్ పంపుతుంది. అందులో ఇవి మాత్రమే ఉంటాయి: ప్రమాద స్థాయి, వినబడిన గరిష్టంగా మూడు మోసపు పద్ధతులు, మరియు (మీరు అనుమతిస్తే) కాలర్ నంబర్."),
        Ui.FA_NEVER to t("It never sends audio, what was said, or your location.", "यह कभी ऑडियो, बातचीत या आपकी लोकेशन नहीं भेजता।", "ఇది ఆడియోను, మాట్లాడినదాన్ని, మీ లొకేషన్‌ను ఎప్పుడూ పంపదు."),
        Ui.FA_WHEN to t("It sends only when a call reaches HIGH risk, and at most once per call. Standard text-message charges may apply.", "यह सिर्फ़ तब भेजता है जब कॉल का ख़तरा ऊँचा हो, और एक कॉल में ज़्यादा से ज़्यादा एक बार। सामान्य SMS शुल्क लग सकता है।", "కాల్ ప్రమాదం అధికం అయినప్పుడు మాత్రమే, ఒక కాల్‌కు గరిష్టంగా ఒకసారి పంపుతుంది. సాధారణ SMS ఛార్జీలు వర్తించవచ్చు."),
        Ui.FA_SAMPLE to t("The exact message (example):", "सटीक संदेश (उदाहरण):", "ఖచ్చితమైన సందేశం (ఉదాహరణ):"),
        Ui.FA_CALLER to t("Include the caller's number: %s", "कॉलर का नंबर शामिल करें: %s", "కాలర్ నంబర్‌ను చేర్చండి: %s"),
        Ui.FA_AUTO_ON to t("I agree: turn on automatic alerts", "मैं सहमत हूँ: स्वचालित अलर्ट चालू करें", "నేను అంగీకరిస్తున్నాను: ఆటోమేటిక్ అలర్ట్‌లు ఆన్ చేయండి"),
        Ui.FA_AUTO_OFF to t("Automatic alerts are ON. Tap to turn off.", "स्वचालित अलर्ट चालू हैं। बंद करने के लिए दबाएं।", "ఆటోమేటిక్ అలర్ట్‌లు ఆన్‌లో ఉన్నాయి. ఆఫ్ చేయడానికి నొక్కండి."),
        Ui.FA_TEST to t("Send a test message (opens messages)", "जाँच संदेश भेजें (मैसेज ऐप खुलेगा)", "పరీక్ష సందేశం పంపండి (మెసేజెస్ యాప్ తెరుచుకుంటుంది)"),
        Ui.FA_LOG to t("What was sent", "क्या भेजा गया", "ఏం పంపబడింది"),
        Ui.FA_LOG_EMPTY to t("Nothing sent yet.", "अभी तक कुछ नहीं भेजा गया।", "ఇంకా ఏదీ పంపలేదు."),
        Ui.FA_NEED_CONTACT to t("Choose a family contact first.", "पहले परिवार का संपर्क चुनें।", "ముందుగా కుటుంబ కాంటాక్ట్‌ను ఎంచుకోండి."),
        Ui.FA_SENT_LINE to t("Family alert sent to %s.", "%s को परिवार अलर्ट भेजा गया।", "%sకు కుటుంబ అలర్ట్ పంపబడింది."),
        Ui.FA_LOG_SENT to t("sent", "भेजा गया", "పంపబడింది"),
        Ui.FA_LOG_FAILED to t("failed", "विफल", "విఫలమైంది"),
        Ui.FA_LOG_TEST to t("test text opened", "जाँच संदेश खोला", "పరీక్ష సందేశం తెరవబడింది"),
        Ui.BLOCK_NUMBER to t("Block this number", "यह नंबर ब्लॉक करें", "ఈ నంబర్‌ను బ్లాక్ చేయండి"),
        Ui.UNBLOCK_NUMBER to t("Unblock this number", "यह नंबर अनब्लॉक करें", "ఈ నంబర్‌ను అన్‌బ్లాక్ చేయండి"),
        Ui.BLOCK_NOTE to t("Blocked. Future calls from this number are rejected. You can undo it here or in settings.", "ब्लॉक हो गया। इस नंबर की आगे की कॉल अस्वीकार होंगी। आप इसे यहाँ या सेटिंग में वापस कर सकते हैं।", "బ్లాక్ చేయబడింది. ఈ నంబర్ నుండి వచ్చే కాల్స్ తిరస్కరించబడతాయి. దీన్ని ఇక్కడ లేదా సెట్టింగ్‌లలో రద్దు చేయవచ్చు."),
        Ui.BLOCK_LIST_FMT to t("Blocked numbers: %d", "ब्लॉक किए नंबर: %d", "బ్లాక్ చేసిన నంబర్లు: %d"),
        Ui.BLOCK_CLEAR to t("Unblock all numbers", "सभी नंबर अनब्लॉक करें", "అన్ని నంబర్లను అన్‌బ్లాక్ చేయండి"),
        Ui.RECOVERY_BUTTON to t("I already shared something: what now?", "मैंने कुछ बता दिया: अब क्या करूँ?", "నేను ఏదైనా చెప్పేశాను: ఇప్పుడేం చేయాలి?"),
        Ui.RECOVERY_TITLE to t("What to do now", "अब क्या करें", "ఇప్పుడు ఏం చేయాలి"),
        Ui.RECOVERY_INTRO to t("Act fast. Tick what happened and follow the steps in order.", "जल्दी करें। जो हुआ उसे चुनें और कदम क्रम से पूरे करें।", "త్వరగా చేయండి. ఏం జరిగిందో ఎంచుకొని, దశలను వరుసగా చేయండి."),
        Ui.RECOVERY_WHAT to t("What happened?", "क्या हुआ?", "ఏం జరిగింది?"),
        Ui.BANK_NUMBER to t("Set my bank's helpline number", "मेरे बैंक की हेल्पलाइन नंबर सेट करें", "నా బ్యాంక్ హెల్ప్‌లైన్ నంబర్ సెట్ చేయండి"),
        Ui.BANK_NUMBER_SET to t("Bank helpline", "बैंक हेल्पलाइन", "బ్యాంక్ హెల్ప్‌లైన్"),
        Ui.URGENT_FIRST to t("Most urgent:", "सबसे ज़रूरी:", "అత్యంత అవసరం:"),
        Ui.PRIVACY to t("Privacy and your data", "निजता और आपका डेटा", "గోప్యత మరియు మీ డేటా"),
        Ui.PRIVACY_BODY to t(
            "Everything happens on this phone. CallGuard has no internet permission, so nothing can be sent out.\n\nAudio is analysed as it arrives and is never saved. Call text is kept only in memory during a call and is gone afterwards.\n\nSaved on this phone: your settings, a scrambled (hashed) form of numbers that called you, and your feedback answers. No audio, no call text.\n\nYou can erase all of it below.",
            "सब कुछ इसी फ़ोन पर होता है। CallGuard के पास इंटरनेट की अनुमति नहीं है, इसलिए कुछ भी बाहर नहीं जा सकता।\n\nऑडियो आते ही जांचा जाता है और कभी सहेजा नहीं जाता। कॉल का टेक्स्ट सिर्फ़ कॉल के दौरान मेमोरी में रहता है, बाद में मिट जाता है।\n\nइस फ़ोन पर सहेजा जाता है: आपकी सेटिंग, कॉल करने वालों के नंबरों का कूटबद्ध (हैश) रूप, और आपके फ़ीडबैक जवाब। कोई ऑडियो या कॉल टेक्स्ट नहीं।\n\nनीचे से आप यह सब मिटा सकते हैं।",
            "ప్రతిదీ ఈ ఫోన్‌లోనే జరుగుతుంది. CallGuard‌కు ఇంటర్నెట్ అనుమతి లేదు, కాబట్టి ఏదీ బయటకు వెళ్లదు.\n\nఆడియో వచ్చినప్పుడే విశ్లేషించబడుతుంది, ఎప్పుడూ సేవ్ చేయబడదు. కాల్ టెక్స్ట్ కాల్ సమయంలో మెమరీలో మాత్రమే ఉంటుంది, తర్వాత పోతుంది.\n\nఈ ఫోన్‌లో సేవ్ అయ్యేవి: మీ సెట్టింగ్‌లు, కాల్ చేసినవారి నంబర్ల గుప్త (హాష్) రూపం, మీ ఫీడ్‌బ్యాక్ సమాధానాలు. ఆడియో లేదా కాల్ టెక్స్ట్ ఉండవు.\n\nవీటన్నింటినీ కింద నుండి తొలగించవచ్చు."),
        Ui.ERASE_ALL to t("Erase all CallGuard data", "CallGuard का सारा डेटा मिटाएं", "CallGuard డేటా మొత్తం తొలగించండి"),
        Ui.ERASE_CONFIRM to t("Erase settings, seen numbers and feedback? This cannot be undone.", "सेटिंग, देखे गए नंबर और फ़ीडबैक मिटाएं? इसे वापस नहीं किया जा सकता।", "సెట్టింగ్‌లు, చూసిన నంబర్లు, ఫీడ్‌బ్యాక్ తొలగించాలా? దీన్ని వెనక్కి తీసుకోలేరు."),
        Ui.ERASE_DONE to t("All data erased.", "सारा डेटा मिटा दिया गया।", "మొత్తం డేటా తొలగించబడింది."),
        Ui.SETTINGS to t("Protection settings", "सुरक्षा सेटिंग्स", "రక్షణ సెట్టింగ్‌లు"),
        Ui.SETTINGS_INTRO to t("Choose which calls CallGuard listens to.", "चुनें कि CallGuard किन कॉल को सुने।", "CallGuard ఏ కాల్స్‌ను వినాలో ఎంచుకోండి."),
        Ui.SCOPE_LABEL to t("Analyse calls from", "इनकी कॉल का विश्लेषण करें", "వీరి కాల్స్‌ను విశ్లేషించండి"),
        Ui.SCOPE_UNKNOWN to t("Unknown numbers only (recommended)", "केवल अनजान नंबर (सुझाया गया)", "తెలియని నంబర్లు మాత్రమే (సూచించబడింది)"),
        Ui.SCOPE_ALL to t("All calls", "सभी कॉल", "అన్ని కాల్స్"),
        Ui.FEEDBACK_Q to t("Was this a scam?", "क्या यह ठगी थी?", "ఇది మోసమేనా?"),
        Ui.FEEDBACK_YES to t("Yes, it was a scam", "हाँ, यह ठगी थी", "అవును, ఇది మోసం"),
        Ui.FEEDBACK_NO to t("No, it was fine", "नहीं, यह ठीक थी", "కాదు, ఇది సరైనదే"),
        Ui.FEEDBACK_UNSURE to t("Not sure", "पक्का नहीं पता", "ఖచ్చితంగా తెలియదు"),
        Ui.FEEDBACK_SAVED to t("Thank you. Saved on this phone only.", "धन्यवाद। सिर्फ़ इसी फ़ोन में सहेजा गया।", "ధన్యవాదాలు. ఈ ఫోన్‌లో మాత్రమే సేవ్ అయింది."),
        Ui.FEEDBACK_SAFE_NOTE to t("Marked as safe: number warnings for this caller are quieter. Requests for codes are still caught.", "सुरक्षित चिह्नित: इस कॉलर के नंबर की चेतावनियाँ कम होंगी। कोड माँगने पर फिर भी चेतावनी मिलेगी।", "సురక్షితంగా గుర్తించబడింది: ఈ కాలర్ నంబర్ హెచ్చరికలు తగ్గుతాయి. కోడ్‌లు అడిగితే మాత్రం ఇంకా హెచ్చరిస్తుంది."),
        Ui.NOTIF_WATCHING_TITLE to t("CallGuard is on", "CallGuard चालू है", "CallGuard ఆన్‌లో ఉంది"),
        Ui.NOTIF_WATCHING_BODY to t("Watching for calls. On-device only. Nothing leaves your phone.", "कॉल पर नज़र रख रहा है। सिर्फ़ फ़ोन पर। कुछ भी बाहर नहीं जाता।", "కాల్స్ కోసం చూస్తోంది. ఫోన్‌లోనే. ఏదీ బయటకు వెళ్లదు."),
        Ui.NOTIF_LISTENING_TITLE to t("CallGuard is protecting this call", "CallGuard इस कॉल की सुरक्षा कर रहा है", "CallGuard ఈ కాల్‌ను రక్షిస్తోంది"),
        Ui.NOTIF_LISTENING_BODY to t("Listening now. On-device only. Nothing leaves your phone.", "अभी सुन रहा है। सिर्फ़ फ़ोन पर। कुछ भी बाहर नहीं जाता।", "ఇప్పుడు వింటోంది. ఫోన్‌లోనే. ఏదీ బయటకు వెళ్లదు."),
        Ui.TILE_ON to t("CallGuard: ON", "CallGuard: चालू", "CallGuard: ఆన్"),
        Ui.TILE_OFF to t("CallGuard: OFF", "CallGuard: बंद", "CallGuard: ఆఫ్"),
        Ui.TR_TITLE to t("Before we ask for anything", "कुछ भी माँगने से पहले", "ఏదైనా అడిగే ముందు"),
        Ui.TR_BODY to t(
            "CallGuard will ask to hear your calls and to know when a call starts, so it can warn you if one sounds like a scam. It never records or saves the audio, and there is no internet permission for it to send anything even if it wanted to — you can check that yourself below. Only your settings, a scrambled form of numbers that called you, and your own feedback are saved, all on this phone.",
            "CallGuard आपकी कॉल सुनने और यह जानने की अनुमति माँगेगा कि कॉल कब शुरू हुई, ताकि ठगी जैसी लगने पर आपको चेतावनी दे सके। यह ऑडियो कभी रिकॉर्ड या सहेजता नहीं। इसके पास इंटरनेट की अनुमति भी नहीं है कि चाहे तो भी कुछ भेज सके — यह आप नीचे ख़ुद जाँच सकते हैं। सिर्फ़ आपकी सेटिंग, कॉल करने वालों के नंबरों का कूटबद्ध रूप, और आपका फ़ीडबैक सहेजा जाता है, सिर्फ़ इसी फ़ोन में।",
            "CallGuard మీ కాల్స్ వినడానికి, కాల్ ఎప్పుడు మొదలైందో తెలుసుకోవడానికి అనుమతి అడుగుతుంది, తద్వారా మోసంలా అనిపిస్తే హెచ్చరించగలదు. ఇది ఆడియోను ఎప్పుడూ రికార్డ్ చేయదు, సేవ్ చేయదు. దీనికి ఇంటర్నెట్ అనుమతి కూడా లేదు, కోరుకున్నా ఏదీ పంపలేదు — దీన్ని మీరే కింద తనిఖీ చేసుకోవచ్చు. మీ సెట్టింగ్‌లు, కాల్ చేసినవారి నంబర్ల గుప్త రూపం, మీ ఫీడ్‌బ్యాక్ మాత్రమే సేవ్ అవుతాయి, అదీ ఈ ఫోన్‌లోనే."),
        Ui.TR_CHECK_FMT to t("Internet access: %s", "इंटरनेट पहुँच: %s", "ఇంటర్నెట్ యాక్సెస్: %s"),
        Ui.TR_CHECK_YES to t("verified NOT requested", "सत्यापित: नहीं माँगी गई", "ధృవీకరించబడింది: అడగలేదు"),
        Ui.TR_CHECK_NO to t("this build has it (the optional online build, for downloads you start yourself)", "इस बिल्ड में है (वैकल्पिक ऑनलाइन बिल्ड, सिर्फ़ आपके शुरू किए डाउनलोड के लिए)", "ఈ బిల్డ్‌లో ఉంది (ఐచ్ఛిక ఆన్‌లైన్ బిల్డ్, మీరు మొదలుపెట్టే డౌన్‌లోడ్‌ల కోసం మాత్రమే)"),
        Ui.TR_READ_ALOUD to t("🔊 Read this aloud", "🔊 ज़ोर से पढ़ें", "🔊 బిగ్గరగా చదవండి"),
        Ui.LIVE_ALERT_PUBLIC_TITLE to t("CallGuard: check your call", "CallGuard: अपनी कॉल देखें", "CallGuard: మీ కాల్‌ను చూడండి"),
        Ui.COACHING_LABEL to t("Tip: what you could say", "सुझाव: आप क्या कह सकते हैं", "సూచన: మీరు ఏమి చెప్పవచ్చు"),
        Ui.UNPROTECTED_NUDGE_FMT to t("%d call(s) from unknown numbers happened while protection was off.", "सुरक्षा बंद रहते %d कॉल अनजान नंबरों से आईं।", "రక్షణ ఆఫ్‌లో ఉన్నప్పుడు తెలియని నంబర్ల నుండి %d కాల్(లు) వచ్చాయి."),
        Ui.UNPROTECTED_DISMISS to t("Got it", "ठीक है", "సరే"),
        Ui.HOME_HISTORY to t("History", "इतिहास", "చరిత్ర"),
        Ui.HIST_TITLE to t("Call history", "कॉल इतिहास", "కాల్ చరిత్ర"),
        Ui.HIST_EMPTY to t("No calls recorded yet.", "अभी कोई कॉल दर्ज नहीं।", "ఇంకా కాల్స్ నమోదు కాలేదు."),
        Ui.HIST_REPORTS_TITLE to t("Reported as missed", "छूटी हुई के रूप में रिपोर्ट की गई", "మిస్ అయినట్లు నివేదించినవి"),
        Ui.HIST_BLOCKED_FMT to t("Blocked numbers: %d (see Settings to undo)", "ब्लॉक किए नंबर: %d (वापस लेने के लिए सेटिंग देखें)", "బ్లాక్ చేసిన నంబర్లు: %d (రద్దు చేయడానికి సెట్టింగ్‌లు చూడండి)"),
        Ui.MISSED_BUTTON to t("Report a call CallGuard missed", "CallGuard से छूटी कॉल की रिपोर्ट करें", "CallGuard మిస్ అయిన కాల్‌ను నివేదించండి"),
        Ui.MISSED_TITLE to t("A call that got through", "एक कॉल जो चूक गई", "తప్పించుకున్న కాల్"),
        Ui.MISSED_INTRO to t("This helps you keep your own record. Nothing is uploaded. No number is required.", "यह आपका अपना रिकॉर्ड रखने में मदद करता है। कुछ अपलोड नहीं होता। नंबर देना ज़रूरी नहीं।", "ఇది మీ స్వంత రికార్డును ఉంచడంలో సహాయపడుతుంది. ఏదీ అప్‌లోడ్ కాదు. నంబర్ ఇవ్వాల్సిన అవసరం లేదు."),
        Ui.MISSED_TAG_OTP to t("Asked for OTP / PIN / CVV", "OTP/PIN/CVV माँगा", "OTP/PIN/CVV అడిగారు"),
        Ui.MISSED_TAG_THREAT to t("Threatened me", "धमकी दी", "బెదిరించారు"),
        Ui.MISSED_TAG_APP to t("Asked me to install an app", "ऐप इंस्टॉल करने को कहा", "యాప్ ఇన్‌స్టాల్ చేయమన్నారు"),
        Ui.MISSED_TAG_MONEY to t("Asked for money", "पैसे माँगे", "డబ్బు అడిగారు"),
        Ui.MISSED_TAG_OTHER to t("Something else felt wrong", "कुछ और गड़बड़ लगा", "ఇంకేదో తప్పుగా అనిపించింది"),
        Ui.MISSED_SAVE to t("Save this report", "यह रिपोर्ट सहेजें", "ఈ నివేదికను సేవ్ చేయండి"),
        Ui.MISSED_SAVED to t("Saved on this phone.", "इसी फ़ोन में सहेजा गया।", "ఈ ఫోన్‌లో సేవ్ అయింది."),
        Ui.FU_TITLE to t("What next", "आगे क्या", "తర్వాత ఏమిటి"),
        Ui.FU_FEEDBACK_STEP to t("Was this a scam?", "क्या यह ठगी थी?", "ఇది మోసమేనా?"),
        Ui.FU_RECOVERY_STEP to t("Did you share anything?", "क्या आपने कुछ बताया?", "మీరు ఏమైనా చెప్పారా?"),
        Ui.FU_RECOVERY_WHY to t("If you shared an OTP, installed an app, or sent money, act fast.", "अगर OTP बताया, ऐप इंस्टॉल किया, या पैसे भेजे, तो जल्दी करें।", "OTP చెప్పినా, యాప్ ఇన్‌స్టాల్ చేసినా, డబ్బు పంపినా, త్వరగా చర్య తీసుకోండి."),
        Ui.FU_BLOCK_STEP to t("Block this number?", "यह नंबर ब्लॉक करें?", "ఈ నంబర్‌ను బ్లాక్ చేయాలా?"),
        Ui.FU_BLOCK_WHY to t("Future calls from this number will be rejected.", "इस नंबर की आगे की कॉल अस्वीकार होंगी।", "ఈ నంబర్ నుండి భవిష్యత్ కాల్స్ తిరస్కరించబడతాయి."),
        Ui.FU_FAMILY_STEP to t("Tell a family member?", "परिवार के किसी सदस्य को बताएं?", "కుటుంబ సభ్యునికి చెప్పాలా?"),
        Ui.FU_FAMILY_WHY to t("A HIGH-risk call is worth a second pair of eyes.", "अधिक ख़तरे वाली कॉल के लिए दूसरी राय अच्छी होती है।", "అధిక ప్రమాదం ఉన్న కాల్‌కు మరొకరి అభిప్రాయం మంచిది."),
        Ui.FU_SKIP to t("Skip", "छोड़ें", "వదిలేయండి"),
        Ui.FU_DONE to t("All done", "सब हो गया", "అన్నీ పూర్తయ్యాయి"),
        Ui.PR_PICK_TITLE to t("Choose a scenario", "एक स्थिति चुनें", "ఒక సన్నివేశాన్ని ఎంచుకోండి"),
        Ui.PR_PICK_INTRO to t("Each one plays the real warning, so you know what to expect.", "हर एक असली चेतावनी दिखाती है, ताकि आपको पता रहे कि क्या उम्मीद करें।", "ప్రతి ఒక్కటి నిజమైన హెచ్చరికను చూపిస్తుంది, మీకు ఏమి ఆశించాలో తెలుస్తుంది."),
        Ui.ACC_SUGGEST_FMT to t("Your phone uses large text. Turn on Accessibility mode too (bigger text, louder, repeated warnings)?", "आपके फ़ोन में बड़ा टेक्स्ट है। सुलभता मोड भी चालू करें (बड़ा टेक्स्ट, तेज़ आवाज़, दोहराई गई चेतावनी)?", "మీ ఫోన్‌లో పెద్ద టెక్స్ట్ ఉంది. యాక్సెసిబిలిటీ మోడ్ కూడా ఆన్ చేయాలా (పెద్ద టెక్స్ట్, ఎక్కువ శబ్దం, పునరావృత హెచ్చరికలు)?"),
        Ui.ACC_SUGGEST_YES to t("Yes, turn it on", "हाँ, चालू करें", "అవును, ఆన్ చేయండి"),
        Ui.ACC_SUGGEST_NO to t("No thanks", "नहीं धन्यवाद", "వద్దు"),
        Ui.SCOPE_HINT to t("Saves battery and is more private: calls from people in your contacts are not analysed.", "बैटरी बचती है और निजता बेहतर रहती है: आपके संपर्कों की कॉल का विश्लेषण नहीं होता।", "బ్యాటరీ ఆదా అవుతుంది, గోప్యత పెరుగుతుంది: మీ కాంటాక్ట్‌ల కాల్స్ విశ్లేషించబడవు."),
    )

    fun get(key: Ui, lang: Lang): String = table.getValue(key).let { (en, hi, te) -> when (lang) { Lang.EN -> en; Lang.HI -> hi; Lang.TE -> te } }
    fun fmt(key: Ui, lang: Lang, vararg args: Any): String = get(key, lang).format(*args)

    /** A language's own name, shown the same way in every language so people can always find theirs. */
    fun name(lang: Lang): String = when (lang) { Lang.EN -> "English"; Lang.HI -> "हिन्दी"; Lang.TE -> "తెలుగు" }

    fun risk(level: RiskLevel, lang: Lang): String = get(when (level) { RiskLevel.LOW -> Ui.RISK_LOW; RiskLevel.MEDIUM -> Ui.RISK_MEDIUM; RiskLevel.HIGH -> Ui.RISK_HIGH }, lang)
    fun alertLine(level: RiskLevel, lang: Lang): String = when (level) { RiskLevel.HIGH -> get(Ui.ALERT_HIGH, lang); RiskLevel.MEDIUM -> get(Ui.ALERT_MEDIUM, lang); RiskLevel.LOW -> "" }

    /** Display text for each option of each setting. */
    fun scopeOption(s: AnalyseScope, lang: Lang) = get(if (s == AnalyseScope.UNKNOWN_ONLY) Ui.SCOPE_UNKNOWN else Ui.SCOPE_ALL, lang)

    fun spokenOption(s: LanguageSetting, lang: Lang) = when (s) {
        LanguageSetting.AUTO -> get(Ui.OPT_AUTO_CALL, lang); LanguageSetting.ENGLISH -> name(Lang.EN); LanguageSetting.HINDI -> name(Lang.HI); LanguageSetting.TELUGU -> name(Lang.TE)
    }
    fun summaryOption(s: SummaryLanguage, lang: Lang) = when (s) {
        SummaryLanguage.SAME_AS_SCREEN -> get(Ui.OPT_SAME_AS_SCREEN, lang); SummaryLanguage.ENGLISH -> name(Lang.EN); SummaryLanguage.HINDI -> name(Lang.HI)
        SummaryLanguage.TELUGU -> name(Lang.TE); SummaryLanguage.MATCH_CALL -> get(Ui.OPT_MATCH_CALL, lang)
    }
}
